int capacity;
int *sala;
int libres;
int ocupados;
void crea_sala(int capacidad);
void elimina_sala();
int reserva_asiento(int id);
int libera_asiento(int asiento);
int estado_asiento(int asiento);
int asientos_libres();
int asientos_ocupados();
int capacidad();
